services:
  - type: web
    name: lyvoxis-wallet-bot
    env: python
    pythonVersion: 3.11.9
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        value: 7986353853:AAGFS_F9nPRwRhb6O-53eTNFFdfRGkNcKq0  # ⛔️不要用 ${BOT_TOKEN}