services:
  - type: web
    name: lyvoxis-wallet
    env: python
    buildCommand: ""
    startCommand: "python main.py"
    envVars:
      - key: BOT_TOKEN
        sync: false
    build:
      environment:
        python: 3.10